version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: kafka-mysql-1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: kafka-zookeeper-1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka-kafka-1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=4
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-app-1
    depends_on:
      - mysql
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKER=kafka:9092
      - DB_HOST=mysql

volumes:
  mysql_data:
  zookeeper_data:
  kafka_data: